// Cities are defined below and exported at the end of the file

export const CHINA_CITIES_ZH = [
  '北京',
  '上海',
  '深圳',
  '广州',
  '成都',
  '杭州',
  '重庆',
  '武汉',
  '西安',
  '苏州',
  '天津',
  '南京',
  '长沙',
  '郑州',
  '东莞',
  '青岛',
  '沈阳',
  '宁波',
  '昆明',
  '大连',
  '哈尔滨',
  '济南',
  '福州',
  '长春',
  '合肥',
  '厦门',
  '南宁',
  '太原',
  '石家庄',
  '南昌',
  '贵阳',
  '兰州',
  '乌鲁木齐',
  '呼和浩特',
  '银川',
  '拉萨'
].sort();

export const CHINA_CITIES_BILINGUAL = [
  // Tier 1 & Major Cities
  { en: 'Beijing', zh: '北京' },
  { en: 'Shanghai', zh: '上海' },
  { en: 'Shenzhen', zh: '深圳' },
  { en: 'Guangzhou', zh: '广州' },
  { en: 'Chengdu', zh: '成都' },
  { en: 'Hangzhou', zh: '杭州' },
  { en: 'Chongqing', zh: '重庆' },
  { en: 'Wuhan', zh: '武汉' },
  { en: 'Xi\'an', zh: '西安' },
  { en: 'Suzhou', zh: '苏州' },
  { en: 'Tianjin', zh: '天津' },
  { en: 'Nanjing', zh: '南京' },

  // Provincial Capitals & Major Cities
  { en: 'Changsha', zh: '长沙' },
  { en: 'Zhengzhou', zh: '郑州' },
  { en: 'Dongguan', zh: '东莞' },
  { en: 'Qingdao', zh: '青岛' },
  { en: 'Shenyang', zh: '沈阳' },
  { en: 'Ningbo', zh: '宁波' },
  { en: 'Kunming', zh: '昆明' },
  { en: 'Dalian', zh: '大连' },
  { en: 'Harbin', zh: '哈尔滨' },
  { en: 'Jinan', zh: '济南' },
  { en: 'Fuzhou', zh: '福州' },
  { en: 'Changchun', zh: '长春' },
  { en: 'Hefei', zh: '合肥' },
  { en: 'Xiamen', zh: '厦门' },
  { en: 'Nanning', zh: '南宁' },
  { en: 'Taiyuan', zh: '太原' },
  { en: 'Shijiazhuang', zh: '石家庄' },
  { en: 'Nanchang', zh: '南昌' },
  { en: 'Guiyang', zh: '贵阳' },
  { en: 'Lanzhou', zh: '兰州' },
  { en: 'Urumqi', zh: '乌鲁木齐' },
  { en: 'Hohhot', zh: '呼和浩特' },
  { en: 'Yinchuan', zh: '银川' },
  { en: 'Lhasa', zh: '拉萨' },
  { en: 'Haikou', zh: '海口' },
  { en: 'Sanya', zh: '三亚' },

  // Tier 2 Cities
  { en: 'Baoding', zh: '保定' },
  { en: 'Tangshan', zh: '唐山' },
  { en: 'Qinhuangdao', zh: '秦皇岛' },
  { en: 'Handan', zh: '邯郸' },
  { en: 'Baotou', zh: '包头' },
  { en: 'Anshan', zh: '鞍山' },
  { en: 'Fushun', zh: '抚顺' },
  { en: 'Benxi', zh: '本溪' },
  { en: 'Dandong', zh: '丹东' },
  { en: 'Jinzhou', zh: '锦州' },
  { en: 'Yingkou', zh: '营口' },
  { en: 'Panjin', zh: '盘锦' },
  { en: 'Liaoyang', zh: '辽阳' },
  { en: 'Jilin', zh: '吉林' },
  { en: 'Siping', zh: '四平' },
  { en: 'Liaoyuan', zh: '辽源' },
  { en: 'Daqing', zh: '大庆' },
  { en: 'Qiqihar', zh: '齐齐哈尔' },
  { en: 'Mudanjiang', zh: '牡丹江' },
  { en: 'Wuxi', zh: '无锡' },
  { en: 'Xuzhou', zh: '徐州' },
  { en: 'Changzhou', zh: '常州' },
  { en: 'Nantong', zh: '南通' },
  { en: 'Yangzhou', zh: '扬州' },
  { en: 'Zhenjiang', zh: '镇江' },
  { en: 'Taizhou (Jiangsu)', zh: '泰州' },
  { en: 'Yancheng', zh: '盐城' },
  { en: 'Wuhu', zh: '芜湖' },
  { en: 'Bengbu', zh: '蚌埠' },
  { en: 'Huainan', zh: '淮南' },
  { en: 'Maanshan', zh: '马鞍山' },
  { en: 'Huaibei', zh: '淮北' },
  { en: 'Tongling', zh: '铜陵' },
  { en: 'Anqing', zh: '安庆' },
  { en: 'Wenzhou', zh: '温州' },
  { en: 'Jiaxing', zh: '嘉兴' },
  { en: 'Huzhou', zh: '湖州' },
  { en: 'Shaoxing', zh: '绍兴' },
  { en: 'Jinhua', zh: '金华' },
  { en: 'Quzhou', zh: '衢州' },
  { en: 'Zhoushan', zh: '舟山' },
  { en: 'Taizhou (Zhejiang)', zh: '台州' },
  { en: 'Lishui', zh: '丽水' },
  { en: 'Putian', zh: '莆田' },
  { en: 'Sanming', zh: '三明' },
  { en: 'Quanzhou', zh: '泉州' },
  { en: 'Zhangzhou', zh: '漳州' },
  { en: 'Nanping', zh: '南平' },
  { en: 'Longyan', zh: '龙岩' },
  { en: 'Yichun', zh: '宜春' },
  { en: 'Ganzhou', zh: '赣州' },
  { en: 'Jingdezhen', zh: '景德镇' },
  { en: 'Pingxiang', zh: '萍乡' },
  { en: 'Jiujiang', zh: '九江' },
  { en: 'Xinyu', zh: '新余' },
  { en: 'Yingtan', zh: '鹰潭' },
  { en: 'Zibo', zh: '淄博' },
  { en: 'Zaozhuang', zh: '枣庄' },
  { en: 'Dongying', zh: '东营' },
  { en: 'Yantai', zh: '烟台' },
  { en: 'Weifang', zh: '潍坊' },
  { en: 'Jining', zh: '济宁' },
  { en: 'Taian', zh: '泰安' },
  { en: 'Weihai', zh: '威海' },
  { en: 'Rizhao', zh: '日照' },
  { en: 'Linyi', zh: '临沂' },
  { en: 'Dezhou', zh: '德州' },
  { en: 'Liaocheng', zh: '聊城' },
  { en: 'Binzhou', zh: '滨州' },
  { en: 'Heze', zh: '菏泽' },
  { en: 'Kaifeng', zh: '开封' },
  { en: 'Luoyang', zh: '洛阳' },
  { en: 'Pingdingshan', zh: '平顶山' },
  { en: 'Anyang', zh: '安阳' },
  { en: 'Hebi', zh: '鹤壁' },
  { en: 'Xinxiang', zh: '新乡' },
  { en: 'Jiaozuo', zh: '焦作' },
  { en: 'Puyang', zh: '濮阳' },
  { en: 'Xuchang', zh: '许昌' },
  { en: 'Luohe', zh: '漯河' },
  { en: 'Sanmenxia', zh: '三门峡' },
  { en: 'Nanyang', zh: '南阳' },
  { en: 'Shangqiu', zh: '商丘' },
  { en: 'Xinyang', zh: '信阳' },
  { en: 'Zhoukou', zh: '周口' },
  { en: 'Zhumadian', zh: '驻马店' },
  { en: 'Xiangyang', zh: '襄阳' },
  { en: 'Yichang', zh: '宜昌' },
  { en: 'Jingzhou', zh: '荆州' },
  { en: 'Jingmen', zh: '荆门' },
  { en: 'Huangshi', zh: '黄石' },
  { en: 'Xiaogan', zh: '孝感' },
  { en: 'Huanggang', zh: '黄冈' },
  { en: 'Ezhou', zh: '鄂州' },
  { en: 'Xianning', zh: '咸宁' },
  { en: 'Suizhou', zh: '随州' },
  { en: 'Zhuzhou', zh: '株洲' },
  { en: 'Xiangtan', zh: '湘潭' },
  { en: 'Hengyang', zh: '衡阳' },
  { en: 'Shaoyang', zh: '邵阳' },
  { en: 'Yueyang', zh: '岳阳' },
  { en: 'Changde', zh: '常德' },
  { en: 'Zhangjiajie', zh: '张家界' },
  { en: 'Chenzhou', zh: '郴州' },
  { en: 'Yongzhou', zh: '永州' },
  { en: 'Huaihua', zh: '怀化' },
  { en: 'Loudi', zh: '娄底' },
  { en: 'Foshan', zh: '佛山' },
  { en: 'Shaoguan', zh: '韶关' },
  { en: 'Zhuhai', zh: '珠海' },
  { en: 'Shantou', zh: '汕头' },
  { en: 'Jiangmen', zh: '江门' },
  { en: 'Zhanjiang', zh: '湛江' },
  { en: 'Maoming', zh: '茂名' },
  { en: 'Zhaoqing', zh: '肇庆' },
  { en: 'Huizhou', zh: '惠州' },
  { en: 'Meizhou', zh: '梅州' },
  { en: 'Shanwei', zh: '汕尾' },
  { en: 'Heyuan', zh: '河源' },
  { en: 'Yangjiang', zh: '阳江' },
  { en: 'Qingyuan', zh: '清远' },
  { en: 'Chaozhou', zh: '潮州' },
  { en: 'Jieyang', zh: '揭阳' },
  { en: 'Yunfu', zh: '云浮' },
  { en: 'Liuzhou', zh: '柳州' },
  { en: 'Guilin', zh: '桂林' },
  { en: 'Wuzhou', zh: '梧州' },
  { en: 'Beihai', zh: '北海' },
  { en: 'Fangchenggang', zh: '防城港' },
  { en: 'Qinzhou', zh: '钦州' },
  { en: 'Guigang', zh: '贵港' },
  { en: 'Yulin', zh: '玉林' },
  { en: 'Baise', zh: '百色' },
  { en: 'Hezhou', zh: '贺州' },
  { en: 'Hechi', zh: '河池' },
  { en: 'Laibin', zh: '来宾' },
  { en: 'Chongzuo', zh: '崇左' },
  { en: 'Zigong', zh: '自贡' },
  { en: 'Panzhihua', zh: '攀枝花' },
  { en: 'Luzhou', zh: '泸州' },
  { en: 'Deyang', zh: '德阳' },
  { en: 'Mianyang', zh: '绵阳' },
  { en: 'Guangyuan', zh: '广元' },
  { en: 'Suining', zh: '遂宁' },
  { en: 'Neijiang', zh: '内江' },
  { en: 'Leshan', zh: '乐山' },
  { en: 'Nanchong', zh: '南充' },
  { en: 'Meishan', zh: '眉山' },
  { en: 'Yibin', zh: '宜宾' },
  { en: 'Guangan', zh: '广安' },
  { en: 'Dazhou', zh: '达州' },
  { en: 'Yaan', zh: '雅安' },
  { en: 'Bazhong', zh: '巴中' },
  { en: 'Ziyang', zh: '资阳' },
  { en: 'Zunyi', zh: '遵义' },
  { en: 'Anshun', zh: '安顺' },
  { en: 'Tongren', zh: '铜仁' },
  { en: 'Qujing', zh: '曲靖' },
  { en: 'Yuxi', zh: '玉溪' },
  { en: 'Baoshan', zh: '保山' },
  { en: 'Zhaotong', zh: '昭通' },
  { en: 'Lijiang', zh: '丽江' },
  { en: 'Puer', zh: '普洱' },
  { en: 'Lincang', zh: '临沧' },
  { en: 'Dali', zh: '大理' },
  { en: 'Xianyang', zh: '咸阳' },
  { en: 'Baoji', zh: '宝鸡' },
  { en: 'Weinan', zh: '渭南' },
  { en: 'Hanzhong', zh: '汉中' },
  { en: 'Ankang', zh: '安康' },
  { en: 'Shangluo', zh: '商洛' },
  { en: 'Tianshui', zh: '天水' },
  { en: 'Baiyin', zh: '白银' },
  { en: 'Wuwei', zh: '武威' },
  { en: 'Zhangye', zh: '张掖' },
  { en: 'Pingliang', zh: '平凉' },
  { en: 'Jiuquan', zh: '酒泉' },
  { en: 'Qingyang', zh: '庆阳' },
  { en: 'Xining', zh: '西宁' },
  { en: 'Shizuishan', zh: '石嘴山' },
  { en: 'Wuzhong', zh: '吴忠' },
].sort((a, b) => a.en.localeCompare(b.en));

export const CHINA_CITIES = CHINA_CITIES_BILINGUAL.map(city => city.en).sort();
