import { supabase } from '../lib/supabase';

export async function seedDummyJobs(userId: string) {
  try {
    const { data: categories } = await supabase
      .from('job_categories')
      .select('id, slug');

    if (!categories || categories.length === 0) {
      throw new Error('Job categories not found. Please ensure categories are created first.');
    }

    const techCat = categories.find((c: any) => c.slug === 'technology')?.id;
    const marketingCat = categories.find((c: any) => c.slug === 'marketing')?.id;
    const financeCat = categories.find((c: any) => c.slug === 'finance')?.id;
    const educationCat = categories.find((c: any) => c.slug === 'education')?.id;
    const opsCat = categories.find((c: any) => c.slug === 'operations')?.id;

    const dummyJobs = [
      {
        poster_id: userId,
        title: 'Senior Full-Stack Developer',
        description: 'We are looking for an experienced full-stack developer to join our team. You will work on building scalable web applications using React and Node.js. Must have 5+ years experience with modern web frameworks.\n\nResponsibilities:\n- Design and develop scalable web applications\n- Collaborate with cross-functional teams\n- Write clean, maintainable code\n- Mentor junior developers',
        location: 'Beijing, China',
        location_country: 'China',
        location_province: 'Beijing',
        location_city: 'Beijing',
        job_type: 'full_time',
        salary_min: 15000,
        salary_max: 25000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'careers@techcompany.com',
        remote_type: 'remote',
        experience_level: 'senior',
        education_required: "Bachelor's Degree",
        skills_required: ['React', 'Node.js', 'PostgreSQL', 'Docker'],
        benefits: ['Health Insurance', 'Competitive Salary', 'Remote Work', 'Professional Development'],
        featured: true,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Marketing Manager',
        description: 'Lead our marketing initiatives and drive brand growth. Manage a team of 3-5 marketing professionals. You will be responsible for developing and executing marketing strategies.\n\nKey Responsibilities:\n- Develop marketing strategies\n- Manage marketing team\n- Analyze campaign performance\n- Build brand awareness',
        location: 'Shanghai, China',
        location_country: 'China',
        location_province: 'Shanghai',
        location_city: 'Shanghai',
        job_type: 'full_time',
        salary_min: 12000,
        salary_max: 18000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: marketingCat,
        status: 'active',
        application_email: 'jobs@marketingfirm.com',
        remote_type: 'hybrid',
        experience_level: 'mid',
        education_required: "Bachelor's Degree",
        skills_required: ['Marketing', 'Team Leadership', 'Analytics', 'Digital Marketing'],
        benefits: ['Performance Bonus', 'Stock Options', 'Flexible Hours'],
        featured: true,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Financial Analyst',
        description: 'Analyze financial data and provide insights to support business decision-making. Work with financial models and help forecast company performance.\n\nWhat You Will Do:\n- Conduct financial analysis\n- Create financial models\n- Present findings to management\n- Monitor market trends',
        location: 'Shenzhen, China',
        location_country: 'China',
        location_province: 'Guangdong',
        location_city: 'Shenzhen',
        job_type: 'full_time',
        salary_min: 10000,
        salary_max: 16000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: financeCat,
        status: 'active',
        application_email: 'apply@financecompany.com',
        remote_type: 'on_site',
        experience_level: 'mid',
        education_required: 'Bachelor\'s Degree in Finance',
        skills_required: ['Financial Analysis', 'Excel', 'Power BI', 'Python'],
        benefits: ['Bonuses', 'Professional Development', 'Health Insurance'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'English Language Instructor',
        description: 'Teach English to students of various levels. Experience in online and offline teaching preferred. Flexible schedule available.\n\nRequirements:\n- Native or fluent English speaker\n- Teaching certification preferred\n- Patient and engaging teaching style',
        location: 'Guangzhou, China',
        location_country: 'China',
        location_province: 'Guangdong',
        location_city: 'Guangzhou',
        job_type: 'part_time',
        salary_min: 200,
        salary_max: 400,
        salary_currency: 'CNY',
        salary_period: 'daily',
        category_id: educationCat,
        status: 'active',
        application_email: 'teacher-jobs@eduplatform.com',
        remote_type: 'hybrid',
        experience_level: 'entry',
        education_required: "Bachelor's Degree",
        skills_required: ['English Teaching', 'Communication', 'Patience'],
        benefits: ['Flexible Schedule', 'Training Provided'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Frontend Developer',
        description: 'Build beautiful and responsive user interfaces using React and TypeScript. Join our innovative startup working on cutting-edge projects.\n\nWhat We Offer:\n- Modern tech stack\n- Collaborative environment\n- Growth opportunities\n- Flexible work arrangements',
        location: 'Hangzhou, China',
        location_country: 'China',
        location_province: 'Zhejiang',
        location_city: 'Hangzhou',
        job_type: 'full_time',
        salary_min: 12000,
        salary_max: 20000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'jobs@startupxyz.com',
        remote_type: 'remote',
        experience_level: 'mid',
        education_required: "Bachelor's Degree",
        skills_required: ['React', 'TypeScript', 'CSS', 'JavaScript'],
        benefits: ['Remote Work', 'Stock Options', 'Unlimited Coffee'],
        featured: true,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Operations Coordinator',
        description: 'Support daily operations and help coordinate between departments. Help streamline processes and improve efficiency.\n\nYour Role:\n- Coordinate daily operations\n- Manage schedules and calendars\n- Support team communication\n- Handle administrative tasks',
        location: 'Chengdu, China',
        location_country: 'China',
        location_province: 'Sichuan',
        location_city: 'Chengdu',
        job_type: 'full_time',
        salary_min: 8000,
        salary_max: 12000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: opsCat,
        status: 'active',
        application_email: 'hr@company.com',
        remote_type: 'on_site',
        experience_level: 'entry',
        education_required: 'High School',
        skills_required: ['Organization', 'Communication', 'Attention to Detail'],
        benefits: ['Training', 'Mentorship'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Data Scientist',
        description: 'Join our AI team to build machine learning models and extract insights from large datasets. Work on cutting-edge projects involving NLP, computer vision, and predictive analytics.\n\nWhat You Will Do:\n- Develop ML models\n- Analyze complex datasets\n- Deploy models to production\n- Collaborate with engineering teams',
        location: 'Beijing, China',
        location_country: 'China',
        location_province: 'Beijing',
        location_city: 'Beijing',
        job_type: 'full_time',
        salary_min: 18000,
        salary_max: 30000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'ai-team@techcompany.com',
        remote_type: 'hybrid',
        experience_level: 'senior',
        education_required: "Master's Degree",
        skills_required: ['Python', 'TensorFlow', 'PyTorch', 'SQL', 'Statistics'],
        benefits: ['Research Budget', 'Conference Attendance', 'GPU Access', 'Flexible Hours'],
        featured: true,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Product Manager',
        description: 'Lead product strategy and roadmap for our SaaS platform. Work closely with engineering, design, and business teams to deliver exceptional products.\n\nResponsibilities:\n- Define product vision\n- Manage product roadmap\n- Conduct user research\n- Analyze product metrics',
        location: 'Shanghai, China',
        location_country: 'China',
        location_province: 'Shanghai',
        location_city: 'Shanghai',
        job_type: 'full_time',
        salary_min: 20000,
        salary_max: 35000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'product@saascompany.com',
        remote_type: 'hybrid',
        experience_level: 'senior',
        education_required: "Bachelor's Degree",
        skills_required: ['Product Strategy', 'User Research', 'Analytics', 'Agile'],
        benefits: ['Stock Options', 'Health Insurance', 'Team Offsites', 'Learning Budget'],
        featured: true,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'UX/UI Designer',
        description: 'Create beautiful and intuitive user experiences for web and mobile applications. Collaborate with product and engineering teams to bring designs to life.\n\nWhat We Are Looking For:\n- 3+ years of UX/UI design experience\n- Proficiency in Figma and Adobe Creative Suite\n- Strong portfolio showcasing your work\n- Understanding of design systems',
        location: 'Hangzhou, China',
        location_country: 'China',
        location_province: 'Zhejiang',
        location_city: 'Hangzhou',
        job_type: 'full_time',
        salary_min: 13000,
        salary_max: 22000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'design@creative.com',
        remote_type: 'remote',
        experience_level: 'mid',
        education_required: "Bachelor's Degree in Design",
        skills_required: ['Figma', 'UI Design', 'UX Research', 'Prototyping'],
        benefits: ['Remote Work', 'Design Tools Budget', 'Flexible Hours'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'DevOps Engineer',
        description: 'Build and maintain our cloud infrastructure. Automate deployments and ensure high availability of our services.\n\nKey Responsibilities:\n- Manage AWS/Azure infrastructure\n- Implement CI/CD pipelines\n- Monitor system performance\n- Ensure security compliance',
        location: 'Shenzhen, China',
        location_country: 'China',
        location_province: 'Guangdong',
        location_city: 'Shenzhen',
        job_type: 'full_time',
        salary_min: 16000,
        salary_max: 28000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'devops@cloud.com',
        remote_type: 'hybrid',
        experience_level: 'mid',
        education_required: "Bachelor's Degree",
        skills_required: ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'Python'],
        benefits: ['Certification Support', 'On-Call Bonus', 'Health Insurance'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Content Marketing Specialist',
        description: 'Create engaging content for our blog, social media, and marketing campaigns. Help us tell our brand story and connect with our audience.\n\nYour Responsibilities:\n- Write blog posts and articles\n- Manage social media content\n- Develop content strategy\n- Optimize content for SEO',
        location: 'Shanghai, China',
        location_country: 'China',
        location_province: 'Shanghai',
        location_city: 'Shanghai',
        job_type: 'full_time',
        salary_min: 9000,
        salary_max: 15000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: marketingCat,
        status: 'active',
        application_email: 'content@marketingco.com',
        remote_type: 'hybrid',
        experience_level: 'entry',
        education_required: "Bachelor's Degree",
        skills_required: ['Content Writing', 'SEO', 'Social Media', 'Copywriting'],
        benefits: ['Flexible Hours', 'Creative Freedom', 'Training'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Sales Executive',
        description: 'Drive revenue growth by acquiring new customers and expanding existing accounts. Work with a dynamic sales team in a fast-paced environment.\n\nWhat You Will Do:\n- Generate new leads\n- Conduct sales presentations\n- Negotiate contracts\n- Meet sales targets',
        location: 'Beijing, China',
        location_country: 'China',
        location_province: 'Beijing',
        location_city: 'Beijing',
        job_type: 'full_time',
        salary_min: 10000,
        salary_max: 20000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: marketingCat,
        status: 'active',
        application_email: 'sales@company.com',
        remote_type: 'hybrid',
        experience_level: 'mid',
        education_required: "Bachelor's Degree",
        skills_required: ['Sales', 'Negotiation', 'CRM', 'Communication'],
        benefits: ['Commission', 'Travel Allowance', 'Health Insurance'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Accountant',
        description: 'Manage financial records and ensure compliance with accounting standards. Work with our finance team to support business operations.\n\nResponsibilities:\n- Prepare financial statements\n- Manage accounts payable/receivable\n- Conduct audits\n- Tax preparation',
        location: 'Guangzhou, China',
        location_country: 'China',
        location_province: 'Guangdong',
        location_city: 'Guangzhou',
        job_type: 'full_time',
        salary_min: 9000,
        salary_max: 14000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: financeCat,
        status: 'active',
        application_email: 'finance@corp.com',
        remote_type: 'on_site',
        experience_level: 'mid',
        education_required: "Bachelor's Degree in Accounting",
        skills_required: ['Accounting', 'Excel', 'Financial Reporting', 'Tax'],
        benefits: ['Stable Income', 'Professional Development', 'Health Insurance'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Investment Analyst',
        description: 'Analyze investment opportunities and provide recommendations to portfolio managers. Work with financial models and market research.\n\nKey Duties:\n- Research investment opportunities\n- Build financial models\n- Monitor portfolio performance\n- Prepare investment reports',
        location: 'Shanghai, China',
        location_country: 'China',
        location_province: 'Shanghai',
        location_city: 'Shanghai',
        job_type: 'full_time',
        salary_min: 15000,
        salary_max: 25000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: financeCat,
        status: 'active',
        application_email: 'careers@investmentfirm.com',
        remote_type: 'on_site',
        experience_level: 'mid',
        education_required: "Master's Degree in Finance",
        skills_required: ['Financial Modeling', 'Bloomberg', 'Excel', 'Valuation'],
        benefits: ['Performance Bonus', 'CFA Sponsorship', 'Health Insurance'],
        featured: true,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Mathematics Teacher',
        description: 'Teach mathematics to high school students. Develop engaging lesson plans and help students achieve their academic goals.\n\nRequirements:\n- Teaching degree or certification\n- Strong math background\n- Excellent communication skills\n- Passion for education',
        location: 'Chengdu, China',
        location_country: 'China',
        location_province: 'Sichuan',
        location_city: 'Chengdu',
        job_type: 'full_time',
        salary_min: 8000,
        salary_max: 12000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: educationCat,
        status: 'active',
        application_email: 'hr@highschool.edu',
        remote_type: 'on_site',
        experience_level: 'mid',
        education_required: "Bachelor's Degree in Mathematics",
        skills_required: ['Mathematics', 'Teaching', 'Curriculum Development'],
        benefits: ['Summer Vacation', 'Pension', 'Health Insurance'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Early Childhood Educator',
        description: 'Work with young children in a nurturing environment. Create fun and educational activities that promote development and learning.\n\nWhat We Offer:\n- Small class sizes\n- Modern facilities\n- Supportive team\n- Professional development',
        location: 'Hangzhou, China',
        location_country: 'China',
        location_province: 'Zhejiang',
        location_city: 'Hangzhou',
        job_type: 'full_time',
        salary_min: 7000,
        salary_max: 10000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: educationCat,
        status: 'active',
        application_email: 'jobs@kindergarten.com',
        remote_type: 'on_site',
        experience_level: 'entry',
        education_required: "Diploma in Early Childhood Education",
        skills_required: ['Child Development', 'Creativity', 'Patience', 'Communication'],
        benefits: ['Training', 'Meals Provided', 'Health Insurance'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Supply Chain Manager',
        description: 'Oversee supply chain operations and optimize logistics processes. Manage vendor relationships and ensure timely delivery of goods.\n\nResponsibilities:\n- Manage inventory levels\n- Coordinate with suppliers\n- Optimize logistics\n- Reduce costs',
        location: 'Shenzhen, China',
        location_country: 'China',
        location_province: 'Guangdong',
        location_city: 'Shenzhen',
        job_type: 'full_time',
        salary_min: 14000,
        salary_max: 22000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: opsCat,
        status: 'active',
        application_email: 'operations@manufacturing.com',
        remote_type: 'on_site',
        experience_level: 'senior',
        education_required: "Bachelor's Degree",
        skills_required: ['Supply Chain', 'Logistics', 'ERP Systems', 'Negotiation'],
        benefits: ['Performance Bonus', 'Health Insurance', 'Career Growth'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Customer Success Manager',
        description: 'Ensure customer satisfaction and drive product adoption. Build strong relationships with clients and help them achieve their goals.\n\nKey Responsibilities:\n- Onboard new customers\n- Provide ongoing support\n- Identify upsell opportunities\n- Reduce churn',
        location: 'Beijing, China',
        location_country: 'China',
        location_province: 'Beijing',
        location_city: 'Beijing',
        job_type: 'full_time',
        salary_min: 11000,
        salary_max: 18000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: opsCat,
        status: 'active',
        application_email: 'success@saas.com',
        remote_type: 'hybrid',
        experience_level: 'mid',
        education_required: "Bachelor's Degree",
        skills_required: ['Customer Service', 'Communication', 'SaaS', 'Problem Solving'],
        benefits: ['Remote Options', 'Growth Opportunities', 'Health Insurance'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'HR Manager',
        description: 'Lead HR initiatives and build a strong company culture. Manage recruitment, employee relations, and performance management.\n\nYour Role:\n- Oversee recruitment\n- Develop HR policies\n- Manage employee relations\n- Drive organizational culture',
        location: 'Shanghai, China',
        location_country: 'China',
        location_province: 'Shanghai',
        location_city: 'Shanghai',
        job_type: 'full_time',
        salary_min: 13000,
        salary_max: 20000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: opsCat,
        status: 'active',
        application_email: 'hr@company.com',
        remote_type: 'hybrid',
        experience_level: 'senior',
        education_required: "Bachelor's Degree in HR",
        skills_required: ['HR Management', 'Recruitment', 'Employee Relations', 'Leadership'],
        benefits: ['Flexible Hours', 'Professional Development', 'Health Insurance'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Mobile App Developer',
        description: 'Build native mobile applications for iOS and Android. Work with cross-platform frameworks and deliver high-quality apps.\n\nWhat You Will Do:\n- Develop mobile apps\n- Integrate APIs\n- Optimize performance\n- Debug and test',
        location: 'Guangzhou, China',
        location_country: 'China',
        location_province: 'Guangdong',
        location_city: 'Guangzhou',
        job_type: 'full_time',
        salary_min: 14000,
        salary_max: 23000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'mobile@devshop.com',
        remote_type: 'remote',
        experience_level: 'mid',
        education_required: "Bachelor's Degree",
        skills_required: ['React Native', 'iOS', 'Android', 'JavaScript', 'Swift'],
        benefits: ['Remote Work', 'Flexible Hours', 'Learning Budget'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'QA Engineer',
        description: 'Ensure software quality through comprehensive testing. Develop test plans and automate testing processes.\n\nResponsibilities:\n- Write test cases\n- Perform manual and automated testing\n- Report and track bugs\n- Improve QA processes',
        location: 'Beijing, China',
        location_country: 'China',
        location_province: 'Beijing',
        location_city: 'Beijing',
        job_type: 'full_time',
        salary_min: 11000,
        salary_max: 18000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'qa@software.com',
        remote_type: 'hybrid',
        experience_level: 'mid',
        education_required: "Bachelor's Degree",
        skills_required: ['Testing', 'Selenium', 'Test Automation', 'Bug Tracking'],
        benefits: ['Training', 'Career Growth', 'Health Insurance'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Backend Developer',
        description: 'Build scalable backend systems and APIs. Work with microservices architecture and cloud technologies.\n\nKey Requirements:\n- 3+ years backend development\n- Strong knowledge of databases\n- Experience with cloud platforms\n- API design expertise',
        location: 'Hangzhou, China',
        location_country: 'China',
        location_province: 'Zhejiang',
        location_city: 'Hangzhou',
        job_type: 'full_time',
        salary_min: 16000,
        salary_max: 26000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'backend@tech.com',
        remote_type: 'hybrid',
        experience_level: 'senior',
        education_required: "Bachelor's Degree",
        skills_required: ['Node.js', 'Python', 'PostgreSQL', 'Redis', 'AWS'],
        benefits: ['Stock Options', 'Remote Flexibility', 'Learning Budget'],
        featured: true,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Social Media Manager',
        description: 'Manage our social media presence across multiple platforms. Create engaging content and grow our online community.\n\nWhat You Will Do:\n- Develop social media strategy\n- Create and schedule content\n- Engage with followers\n- Analyze performance metrics',
        location: 'Shanghai, China',
        location_country: 'China',
        location_province: 'Shanghai',
        location_city: 'Shanghai',
        job_type: 'full_time',
        salary_min: 10000,
        salary_max: 16000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: marketingCat,
        status: 'active',
        application_email: 'social@brand.com',
        remote_type: 'remote',
        experience_level: 'mid',
        education_required: "Bachelor's Degree",
        skills_required: ['Social Media', 'Content Creation', 'Analytics', 'Community Management'],
        benefits: ['Remote Work', 'Creative Freedom', 'Flexible Hours'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Business Analyst',
        description: 'Analyze business processes and identify opportunities for improvement. Work with stakeholders to gather requirements and drive digital transformation.\n\nKey Responsibilities:\n- Gather business requirements\n- Analyze processes\n- Document specifications\n- Support implementation',
        location: 'Shenzhen, China',
        location_country: 'China',
        location_province: 'Guangdong',
        location_city: 'Shenzhen',
        job_type: 'full_time',
        salary_min: 12000,
        salary_max: 19000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: opsCat,
        status: 'active',
        application_email: 'business@consulting.com',
        remote_type: 'hybrid',
        experience_level: 'mid',
        education_required: "Bachelor's Degree",
        skills_required: ['Business Analysis', 'Requirements Gathering', 'SQL', 'Process Mapping'],
        benefits: ['Training', 'Career Development', 'Health Insurance'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Graphic Designer',
        description: 'Create visually stunning designs for digital and print media. Work on branding, marketing materials, and digital assets.\n\nWhat We Are Looking For:\n- Creative portfolio\n- Proficiency in Adobe Creative Suite\n- Strong eye for design\n- Attention to detail',
        location: 'Chengdu, China',
        location_country: 'China',
        location_province: 'Sichuan',
        location_city: 'Chengdu',
        job_type: 'full_time',
        salary_min: 8000,
        salary_max: 13000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: marketingCat,
        status: 'active',
        application_email: 'design@agency.com',
        remote_type: 'remote',
        experience_level: 'entry',
        education_required: "Bachelor's Degree in Design",
        skills_required: ['Photoshop', 'Illustrator', 'InDesign', 'Typography'],
        benefits: ['Remote Work', 'Creative Projects', 'Portfolio Building'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Cybersecurity Specialist',
        description: 'Protect our systems from security threats. Monitor networks, conduct security audits, and respond to incidents.\n\nResponsibilities:\n- Monitor security systems\n- Conduct vulnerability assessments\n- Respond to security incidents\n- Implement security policies',
        location: 'Beijing, China',
        location_country: 'China',
        location_province: 'Beijing',
        location_city: 'Beijing',
        job_type: 'full_time',
        salary_min: 17000,
        salary_max: 28000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'security@corp.com',
        remote_type: 'hybrid',
        experience_level: 'senior',
        education_required: "Bachelor's Degree in Computer Science",
        skills_required: ['Network Security', 'Penetration Testing', 'SIEM', 'Incident Response'],
        benefits: ['Certification Support', 'On-Call Bonus', 'Health Insurance'],
        featured: true,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Video Editor',
        description: 'Edit videos for marketing campaigns, social media, and internal communications. Work with creative teams to produce engaging video content.\n\nKey Skills Required:\n- Video editing expertise\n- Motion graphics\n- Color grading\n- Sound design',
        location: 'Shanghai, China',
        location_country: 'China',
        location_province: 'Shanghai',
        location_city: 'Shanghai',
        job_type: 'contract',
        salary_min: 300,
        salary_max: 600,
        salary_currency: 'CNY',
        salary_period: 'daily',
        category_id: marketingCat,
        status: 'active',
        application_email: 'video@production.com',
        remote_type: 'remote',
        experience_level: 'mid',
        education_required: 'Portfolio Required',
        skills_required: ['Premiere Pro', 'After Effects', 'Video Editing', 'Motion Graphics'],
        benefits: ['Flexible Schedule', 'Remote Work', 'Creative Projects'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Project Manager',
        description: 'Lead cross-functional teams to deliver projects on time and within budget. Manage project scope, timeline, and resources.\n\nYour Responsibilities:\n- Define project scope\n- Manage timelines and budgets\n- Coordinate team members\n- Report to stakeholders',
        location: 'Hangzhou, China',
        location_country: 'China',
        location_province: 'Zhejiang',
        location_city: 'Hangzhou',
        job_type: 'full_time',
        salary_min: 15000,
        salary_max: 24000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: opsCat,
        status: 'active',
        application_email: 'projects@company.com',
        remote_type: 'hybrid',
        experience_level: 'senior',
        education_required: "Bachelor's Degree",
        skills_required: ['Project Management', 'Agile', 'Scrum', 'Leadership'],
        benefits: ['PMP Certification Support', 'Health Insurance', 'Career Growth'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Copywriter',
        description: 'Write compelling copy for websites, ads, and marketing campaigns. Help shape our brand voice and connect with audiences.\n\nWhat You Will Do:\n- Write marketing copy\n- Develop brand messaging\n- Collaborate with design teams\n- Edit and proofread content',
        location: 'Guangzhou, China',
        location_country: 'China',
        location_province: 'Guangdong',
        location_city: 'Guangzhou',
        job_type: 'full_time',
        salary_min: 9000,
        salary_max: 14000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: marketingCat,
        status: 'active',
        application_email: 'copy@agency.com',
        remote_type: 'remote',
        experience_level: 'entry',
        education_required: "Bachelor's Degree",
        skills_required: ['Copywriting', 'Creative Writing', 'SEO', 'Editing'],
        benefits: ['Remote Work', 'Flexible Hours', 'Creative Freedom'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Legal Counsel',
        description: 'Provide legal advice and support to the business. Draft and review contracts, ensure compliance, and manage legal risks.\n\nResponsibilities:\n- Review contracts\n- Ensure regulatory compliance\n- Manage legal disputes\n- Provide legal advice',
        location: 'Beijing, China',
        location_country: 'China',
        location_province: 'Beijing',
        location_city: 'Beijing',
        job_type: 'full_time',
        salary_min: 18000,
        salary_max: 30000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: financeCat,
        status: 'active',
        application_email: 'legal@corporation.com',
        remote_type: 'on_site',
        experience_level: 'senior',
        education_required: 'Law Degree',
        skills_required: ['Contract Law', 'Corporate Law', 'Compliance', 'Negotiation'],
        benefits: ['Performance Bonus', 'Health Insurance', 'Professional Development'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Data Analyst',
        description: 'Analyze business data to uncover insights and support decision-making. Create dashboards and reports for stakeholders.\n\nKey Responsibilities:\n- Analyze data trends\n- Create visualizations\n- Build dashboards\n- Present insights',
        location: 'Shanghai, China',
        location_country: 'China',
        location_province: 'Shanghai',
        location_city: 'Shanghai',
        job_type: 'full_time',
        salary_min: 12000,
        salary_max: 19000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'data@analytics.com',
        remote_type: 'hybrid',
        experience_level: 'mid',
        education_required: "Bachelor's Degree",
        skills_required: ['SQL', 'Excel', 'Tableau', 'Python', 'Statistics'],
        benefits: ['Learning Budget', 'Flexible Hours', 'Health Insurance'],
        featured: false,
        published_at: new Date().toISOString(),
      },
      {
        poster_id: userId,
        title: 'Technical Writer',
        description: 'Create clear and comprehensive technical documentation. Work with engineers to document APIs, SDKs, and user guides.\n\nWhat You Will Do:\n- Write technical documentation\n- Create user guides\n- Document APIs\n- Maintain documentation site',
        location: 'Shenzhen, China',
        location_country: 'China',
        location_province: 'Guangdong',
        location_city: 'Shenzhen',
        job_type: 'full_time',
        salary_min: 10000,
        salary_max: 16000,
        salary_currency: 'CNY',
        salary_period: 'monthly',
        category_id: techCat,
        status: 'active',
        application_email: 'docs@techcompany.com',
        remote_type: 'remote',
        experience_level: 'mid',
        education_required: "Bachelor's Degree",
        skills_required: ['Technical Writing', 'Markdown', 'Git', 'API Documentation'],
        benefits: ['Remote Work', 'Flexible Hours', 'Learning Opportunities'],
        featured: false,
        published_at: new Date().toISOString(),
      },
    ];

    const { data, error } = await supabase
      .from('jobs')
      .insert(dummyJobs)
      .select();

    if (error) throw error;

    console.log(`Successfully seeded ${data?.length || 0} dummy jobs`);
    return { success: true, count: data?.length || 0 };
  } catch (error) {
    console.error('Failed to seed dummy jobs:', error);
    return { success: false, error };
  }
}
