import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_KEY;

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing environment variables. Ensure VITE_SUPABASE_URL and SUPABASE_SERVICE_KEY are set.');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseServiceKey);

const marketplaceListings = [
  {
    title: 'iPhone 14 Pro Max 256GB',
    title_zh: 'iPhone 14 Pro Max 256GB',
    description: 'Barely used iPhone 14 Pro Max in excellent condition. Includes original box, charger, and case. No scratches on screen.',
    description_zh: '几乎全新的iPhone 14 Pro Max，状况极佳。包含原装盒、充电器和保护壳。屏幕无划痕。',
    category: 'electronics',
    subcategory: 'phones',
    price_rmb: 6500,
    currency: 'CNY',
    negotiable: true,
    condition: 'like-new',
    brand: 'Apple',
    location_province: 'Shanghai',
    location_city: 'Shanghai',
    location_area: 'Pudong',
    image_urls: ['https://images.unsplash.com/photo-1632661674596-df8be070a5c5?auto=format&fit=crop&w=600&q=80'],
    contact_method: 'in_app',
    status: 'published',
    user_id: null, // Will need to be set to a real user ID
  },
  {
    title: 'IKEA Sofa - 3 Seater',
    title_zh: '宜家沙发 - 三人座',
    description: 'Comfortable 3-seater sofa from IKEA. Light gray fabric. Perfect for small apartments. Selling due to relocation.',
    description_zh: '宜家舒适的三人座沙发，浅灰色布料。适合小公寓。因搬家出售。',
    category: 'furniture',
    price_rmb: 1200,
    currency: 'CNY',
    negotiable: true,
    condition: 'used',
    brand: 'IKEA',
    location_province: 'Beijing',
    location_city: 'Beijing',
    location_area: 'Chaoyang',
    image_urls: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80'],
    contact_method: 'in_app',
    status: 'published',
    user_id: null,
  },
  {
    title: 'Mountain Bike - Giant ATX 27.5',
    title_zh: '山地自行车 - 捷安特 ATX 27.5',
    description: 'Well-maintained Giant mountain bike. 27.5 inch wheels, 21-speed gear system. Great for weekend rides.',
    description_zh: '保养良好的捷安特山地车。27.5英寸车轮，21速变速系统。适合周末骑行。',
    category: 'sports',
    subcategory: 'bicycles',
    price_rmb: 800,
    currency: 'CNY',
    negotiable: true,
    condition: 'used',
    brand: 'Giant',
    location_province: 'Guangdong',
    location_city: 'Shenzhen',
    location_area: 'Nanshan',
    image_urls: ['https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?auto=format&fit=crop&w=600&q=80'],
    contact_method: 'wechat',
    contact_wechat: 'bikeowner123',
    status: 'published',
    user_id: null,
  },
  {
    title: 'Canon EOS R6 Camera Body',
    title_zh: '佳能 EOS R6 机身',
    description: 'Canon EOS R6 mirrorless camera body. Low shutter count (5000). Comes with 2 batteries and original accessories.',
    description_zh: '佳能EOS R6微单相机机身。快门次数少(5000次)。附带2块电池和原装配件。',
    category: 'electronics',
    subcategory: 'cameras',
    price_rmb: 12000,
    currency: 'CNY',
    negotiable: false,
    condition: 'like-new',
    brand: 'Canon',
    location_province: 'Zhejiang',
    location_city: 'Hangzhou',
    image_urls: ['https://images.unsplash.com/photo-1606980624361-a8b9ca2cfab3?auto=format&fit=crop&w=600&q=80'],
    contact_method: 'in_app',
    status: 'published',
    user_id: null,
  },
  {
    title: 'Office Desk with Drawers',
    title_zh: '带抽屉的办公桌',
    description: 'Solid wood office desk with 3 drawers. 120cm x 60cm. Excellent condition, barely used.',
    description_zh: '实木办公桌，3个抽屉。尺寸120cm x 60cm。状况极佳，几乎未使用。',
    category: 'furniture',
    price_rmb: 600,
    currency: 'CNY',
    negotiable: true,
    condition: 'like-new',
    dimensions: 'L120cm x W60cm x H75cm',
    location_province: 'Shanghai',
    location_city: 'Shanghai',
    location_area: 'Jing\'an',
    image_urls: ['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=600&q=80'],
    contact_method: 'in_app',
    status: 'published',
    user_id: null,
  },
  {
    title: 'Nike Air Max 2023 - Size 42',
    title_zh: 'Nike Air Max 2023 - 42码',
    description: 'Brand new Nike Air Max 2023 sneakers, still in box. Size EU 42. Never worn, perfect gift!',
    description_zh: '全新Nike Air Max 2023运动鞋，原盒未拆。欧码42。从未穿过，完美礼物！',
    category: 'clothing',
    subcategory: 'shoes',
    price_rmb: 850,
    currency: 'CNY',
    negotiable: false,
    condition: 'new',
    brand: 'Nike',
    size: 'EU 42',
    color: 'Black/White',
    location_province: 'Guangdong',
    location_city: 'Guangzhou',
    image_urls: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80'],
    contact_method: 'in_app',
    status: 'published',
    user_id: null,
  },
  {
    title: 'PlayStation 5 with 2 Controllers',
    title_zh: 'PlayStation 5 双手柄套装',
    description: 'PS5 console with 2 DualSense controllers and 5 games. Everything in perfect working condition.',
    description_zh: 'PS5主机，2个DualSense手柄和5款游戏。一切运行完美。',
    category: 'electronics',
    subcategory: 'gaming',
    price_rmb: 3500,
    currency: 'CNY',
    negotiable: true,
    condition: 'used',
    brand: 'Sony',
    location_province: 'Beijing',
    location_city: 'Beijing',
    location_area: 'Haidian',
    image_urls: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=600&q=80'],
    contact_method: 'phone',
    status: 'published',
    user_id: null,
  },
  {
    title: 'MacBook Air M2 13" 256GB',
    title_zh: 'MacBook Air M2 13寸 256GB',
    description: 'MacBook Air M2 in Space Gray. 8GB RAM, 256GB SSD. 6 months old, still under warranty. Like new condition.',
    description_zh: 'MacBook Air M2深空灰色。8GB内存，256GB固态硬盘。使用6个月，仍在保修期内。近乎全新。',
    category: 'electronics',
    subcategory: 'laptops',
    price_rmb: 7200,
    currency: 'CNY',
    negotiable: false,
    condition: 'like-new',
    brand: 'Apple',
    color: 'Space Gray',
    location_province: 'Shanghai',
    location_city: 'Shanghai',
    location_area: 'Xuhui',
    image_urls: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80'],
    contact_method: 'in_app',
    status: 'published',
    user_id: null,
  },
  {
    title: 'Dining Table Set - 4 Chairs',
    title_zh: '餐桌套装 - 4把椅子',
    description: 'Modern dining table with 4 chairs. White finish, perfect for small dining areas. Excellent condition.',
    description_zh: '现代餐桌配4把椅子。白色涂装，适合小餐厅。状况极佳。',
    category: 'furniture',
    price_rmb: 1500,
    currency: 'CNY',
    negotiable: true,
    condition: 'used',
    location_province: 'Jiangsu',
    location_city: 'Nanjing',
    image_urls: ['https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=600&q=80'],
    contact_method: 'in_app',
    status: 'published',
    user_id: null,
  },
  {
    title: 'Electric Scooter - Xiaomi Mi',
    title_zh: '电动滑板车 - 小米',
    description: 'Xiaomi electric scooter in great condition. Max speed 25km/h, range 30km. Perfect for commuting.',
    description_zh: '小米电动滑板车状况良好。最高时速25公里，续航30公里。适合通勤。',
    category: 'sports',
    subcategory: 'scooters',
    price_rmb: 1100,
    currency: 'CNY',
    negotiable: true,
    condition: 'used',
    brand: 'Xiaomi',
    location_province: 'Guangdong',
    location_city: 'Shenzhen',
    location_area: 'Futian',
    image_urls: ['https://images.unsplash.com/photo-1609779333097-68c1c6f6649e?auto=format&fit=crop&w=600&q=80'],
    contact_method: 'wechat',
    contact_wechat: 'scooter_seller',
    status: 'published',
    user_id: null,
  },
];

async function seedMarketplace() {
  console.log('🛒 Seeding marketplace_listings...');
  
  // Note: user_id will need to be set or handled via database trigger
  const { data, error } = await supabase
    .from('marketplace_listings')
    .insert(marketplaceListings)
    .select();

  if (error) {
    console.error('❌ Error seeding marketplace:', error.message);
  } else {
    console.log(`✅ Successfully seeded ${data.length} marketplace listings`);
  }
}

seedMarketplace();
